### ISSUE TITLE
Debug information for a detector

### ISSUE THREAD

**Issue by philip-harr** [siemens/drace#20]
To debug a detector using drace-test.exe or drrun.exe with the drace-client.dll the sources of the detector must be mentioned in the according cmake files.

Is it okay to just mention them statically in the cmake file (like shown in the pictures)

![image](https://user-images.githubusercontent.com/52499923/63700308-ee104e00-c822-11e9-893f-75e1968f9186.png)
(CMakeLists of drace-test)

![image](https://user-images.githubusercontent.com/52499923/63700344-02ece180-c823-11e9-8423-2c48b7919a54.png)
(CMake of drace-client)

**Comment by fmoessbauer** [comment]
We cannot adopt to this solution, as the detector sources must not be part of DRace itself. Instead they are build in their own library which is then linked (dynamically) to DRace.

I'm sure there is another - correct - solution for this issue.

**Comment by fmoessbauer** [comment]
With the changes in [refactor/rtload](https://github.com/siemens/drace/tree/refactor/rtload) we should check if the issue persists.

**Comment by fmoessbauer** [comment]
Fixed in 15fdeb471d79e8d86c571412b079f6ceffa605b6.

When executing `configure_DynamoRIO_client` some global flags like `CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}` are emptied out. For details, see also https://github.com/DynamoRIO/dynamorio/blob/master/make/DynamoRIOConfig.cmake.in#L122

_Note: this also improves performance as this also applies to the optimize flags._
